### ISSUE TITLE
Bug uploading text

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#117]
```
NoMethodError (undefined method `content' for nil:NilClass):
  app/indexers/text_indexer.rb:14:in `tei_as_json'
  app/indexers/text_indexer.rb:6:in `block in generate_solr_document'
  app/indexers/text_indexer.rb:5:in `generate_solr_document'
```

**Comment by jcoyne** [comment]
``` ruby
t = Text.find('sn009x784')
t.tei
=> #<GenericFile id: "9g54xh65x" ...
t.tei.original_file
=> nil
```
