### ISSUE TITLE
Undefined method errors in resque

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#197]
```
undefined method `pcdm_object?' for nil:NilClass

/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/hydra-pcdm-463d73a2fd4b/lib/hydra/pcdm/models/concerns/object_behavior.rb:43:in `select'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/hydra-pcdm-463d73a2fd4b/lib/hydra/pcdm/models/concerns/object_behavior.rb:43:in `in_objects'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:11:in `generic_works'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/file_set/belongs_to_works.rb:16:in `generic_work_ids'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:16:in `block in generate_solr_document'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:6:in `tap'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/file_set_indexing_service.rb:6:in `generate_solr_document'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.3/lib/active_fedora/indexing.rb:23:in `to_solr'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-9.3.0/app/models/concerns/hydra/access_controls/permissions.rb:15:in `to_solr'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/human_readable_type.rb:15:in `to_solr'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-9.3.0/app/models/concerns/hydra/access_controls/embargoable.rb:37:in `to_solr'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.3/lib/active_fedora/indexing.rb:32:in `update_index'
/opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/jobs/create_derivatives_job.rb:10:in `perform'
```

**Comment by val99erie** [comment]
I see the "undefined method `pcdm_object?' for nil:NilClass" error in resque for CharacterizeJob, IngestFileJob, and CreateDerivativesJob

**Comment by jcoyne** [comment]
Blocked until server is back up.  We need to see what `FileSet#aggregated_by` is returning, I suspect it may have been returning nils. this may already be fixed.
