### ISSUE TITLE
can't call member ids

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#198]
```
irb(main):001:0> t = Text.find('1n79h430f')
Attempted to init base path `prod`, but it already exists
=> #<Text id: "1n79h430f", owner: nil, label: nil, depositor: "system", relative_path: nil, import_url: nil, part_of: [#<ActiveTriples::Resource:0xb8b758(#<ActiveTriples::Resource:0x00000001716eb0>)>], resource_type: [], title: ["Helmar"], creator: ["Fanny Lewald"], contributor: [], description: [], tag: [], rights: ["http://creativecommons.org/publicdomain/mark/1.0/"], publisher: ["Otto Janke"], date_created: [], date_uploaded: nil, date_modified: nil, subject: [], language: ["German"], identifier: ["lew1880.0001.007"], based_near: [], related_url: [], bibliographic_citation: [], source: [], date_issued: "1880", extent: ["1 novel in 1 volume"], series: [], note: [], publication_place: [], description_standard: [], editor: ["Fanny Lewald"], sponsor: [], funder: [], researcher: [], head_id: "1n79h430f/members/c9d01839-1018-465e-a7af-6d15d5d59817", tail_id: "1n79h430f/members/07b0926e-97a8-456f-bf4d-4a926608de94", representative_id: "c534fp05b", thumbnail_id: nil, embargo_id: nil, lease_id: nil, admin_set_id: "lew", tei_id: "b2773v74n">
irb(main):002:0> t.member_ids
TypeError: no implicit conversion from nil to integer
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `delete_at'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
... 301 levels...
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:26:in `ids_reader'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/builder.rb:18:in `block in define_readers'
```

**Comment by val99erie** [comment]
This might be related.  I was unable to update the index for the same object, but the update_index works after you run file_set_ids on the object.

```
irb(main):008:0> t.update_index
TypeError: no implicit conversion from nil to integer
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `delete_at'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:57:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/activefedora-aggregation-24a2d140ecb9/lib/active_fedora/aggregation/association.rb:61:in `create_linked_list'
... 311 levels...
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/indexers/curation_concerns/work_indexing_service.rb:5:in `generate_solr_document'
    from /opt/goldenseal/releases/20151016020030/app/indexers/base_work_indexer.rb:3:in `generate_solr_document'
    from /opt/goldenseal/releases/20151016020030/app/indexers/text_indexer.rb:5:in `generate_solr_document'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.3/lib/active_fedora/indexing.rb:23:in `to_solr'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-31684a3eb773/curation_concerns-models/app/models/concerns/curation_concerns/human_readable_type.rb:15:in `to_solr'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-9.3.0/app/models/concerns/hydra/access_controls/permissions.rb:15:in `to_solr'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-access-controls-9.3.0/app/models/concerns/hydra/access_controls/embargoable.rb:37:in `to_solr'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.4.3/lib/active_fedora/indexing.rb:32:in `update_index'
    from (irb):8
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:8:in `require'
    from bin/rails:8:in `<main>'irb(main):009:0> 
irb(main):010:0* t.file_set_ids
=> ["b2773v74n", "c534fp05b", "j3860702d", "0c483j470", "h989r334f", "9w032316c", "5138jd92m", "v979v320v", "hq37vn616", "bc386j260", "nz805z711", "qn59q410g", "mk61rh020", "5712m663n", "1n79h431q", "tb09j5732", "3197xm13h", "pn89d663n", "kp78gg470", "pr76f347h", "jd472w49x", "m613mx67m", "fb494850b", "d791sg277", "k643b125m", "t435gd07x", "ks65hc370", "c247ds19f", "0c483j488", "s1784k82c", "q811kj738", "v979v3214", "mg74qm21z", "x059c742j", "gx41mh92t", "st74cq573", "qj72p7206", "x633f1090", "2r36tx63q", "zp38wc685", "v405s941w", "37720c83m", "x059c743t", "db78tc035", "nk322d431", "jd472w50p", "9w032317n", "6w924b91d", "dn39x164p", "f1881m02w", "k643b126w", "z029p484q", "2f75r813w", "kk91fk62k", "nk322d449", "j6731387r", "73666457w", "fb494851m", "dv13zt29d", "9019s2486", "1831ck07c", "j67313881", "fx719m49w", "1n79h4320", "0k225b13n", "qr46r089p", "k643b1275", "w9505051c", "pn89d664x", "k930bx11b", "p5547r59j", "cj82k742g", "kd17cs934", "pr76f348s", "4t64gn27q", "f4752g809", "qr46r090f", "1j92g760n", "pr76f3492", "tb09j574b", "rr171x292", "4j03cz72k", "nv9352930", "m039k4989", "nv9352948", "5999n346g", "z603qx485", "fq977t91d", "ks65hc388", "gq67jr29s", "8p58pd01g", "cc08hf731", "ft848q694", "47429931q", "ms35t874s", "4x51hj112", "736664585", "rx913p98q", "hq37vn62g", "w3763690k", "hh63sw02g", "g158bh34t", "js956f89w", "tm70mv21t", "p2676v56g", "3n203z16t", "cv43nw929", "3t945q80c", "v692t630k", "cz30ps80r", "m039k499k", "nz805z729", "th83kz43m", "r207tp39b", "f7623c66q", "9019s249g", "h702q641c", "cf95jb516", "wp988j91f", "cf95jb52g", "fn106z095", "5t34sj67b", "rn301143j", "v979v322d", "h702q642n", "ws859f830", "7p88cg612", "x346d423k", "tb09j575m", "zg64tm00z", "474299320", "pz50gw25s", "pc289j13p", "sb397833f", "jh343s427", "gf06g2753", "h128nd75q", "8623hx773", "3n203z173", "vx021f16r", "pn89d6656", "9880vr00j", "4b29b6075", "tb09j576w", "1c18df83h", "kw52j8156", "v979v323p", "hd76s013x", "9g54xh74w", "s7526c567", "fx719m50n", "rj4304642", "xk81jk42v", "sj1392036", "ff365535g", "mc87pq327", "5d86p032c", "m326m181c", "44558d438", "nc580m71q", "dv13zt305", "z316q164g", "5m60qr95r", "4f16c291q", "3n203z18c", "ff365536r", "sq87bt68c", "08612n63v", "n009w2390", "k930bx12m", "r207tp403", "v979v324z", "8336h203f", "tq57nr08s", "cn69m420z", "5t34sj68m", "d217qp58s", "ws859f848", "s1784k83n", "vq27zn55t", "000000107", "7w62f833c", "v979v3257", "np193924b", "765371442", "tx31qh78r", "02870v87z", "z316q165r", "n009w240r", "ms35t8752", "n870zq887", "j098zb17n", "t148fh321", "mk61rh038", "4f16c2920", "1g05fb727", "vt150j41v", "7d278t10t", "q811kj74j", "6682x401g", "pn89d666g", "7d278t113", "ht24wj541", "qj72p721g", "5138jd93w", "wm117n995", "6395w7174", "1544bp17c", "c247ds206", "6t053g11g", "h415p964f", "h128nd760", "c534fp06m", "2v23vt469", "5d86p033n", "cc08hf749", "qf85nb44j", "kp78gg488", "8s45q886t", "cf95jb53r", "9z902z94k", "qb98mf563", "st74cq58c", "hq37vn63r", "xg94hp65x", "0v8380680", "cn69m4217", "np193925m", "bv73c0470", "d791sg28h", "xp68kg28j", "7s75dc41t", "d791sg29s", "1n79h4338", "37720c84w", "m900nt552", "kk91fk63v", "h989r335q", "q237hs00g", "9880vr01t", "5999n347r", "xg94hp666", "8623hx78c", "np193926w", "1c18df84s", "z316q1661", "nz805z73k", "t148fh339", "m900nt56b", "1j92g761x", "6682x402r", "bg257f11m", "gx41mh933", "b8515n44d", "0z708w479", "gt54kn09j", "m613mx68w", "4q77fr47z", "707957749", "474299338", "gt54kn109", "ms35t876b", "8g84mm437", "wd375w36m", "kh04dp770", "r781wg04p", "pz50gw262", "r781wg05z", "rb68xb945", "6108vb31r", "6d56zw69h", "m039k5004", "8623hx79n", "02870v887", "fj236222n", "8910jt630", "3n203z19n", "7m01bk82b", "f1881m035", "t722h892r", "xd07gs80t", "cc08hf75k", "x920fw91t", "zc77sq142", "qv33rw719", "np1939275", "mk61rh04j", "f7623c670", "gb19f588x", "ng451h60f", "pg15bd94x", "0v8380698", "tb09j5775", "cr56n108x", "0p096703x", "k06987564", "2j62s496p", "tb09j578f", "1r66j1238", "z029p4850", "1z40ks843", "x059c7443", "mk61rh05t", "9306sz33n", "d791sg30j", "nk322d45k", "m900nt57m", "rv042t124", "4j03cz73v", "n870zq89h", "0z708w48k", "t722h8931", "jd472w51z", "6969z090p", "r494vk20t", "8k71nh16k", "v692t631v", "8k71nh17v", "9019s2507", "rx913p990", "8w32r5659"]
irb(main):011:0> t.update_index
=> {"responseHeader"=>{"status"=>0, "QTime"=>20}}
irb(main):012:0> t.id
=> "1n79h430f"
```

**Comment by jcoyne** [comment]
add lib/active_fedora/aggregation/association.rb to line 57

```
raise "can't find #{first_id.inspect} in the list #{@owner.id} with #{remainder.size} remaining" unless index
```

**Comment by jcoyne** [comment]
It appears we have two full sets of proxies for the sets in the work:
https://gist.github.com/jcoyne/ed9dfc340e7e80f3670d

**Comment by jcoyne** [comment]
reopened because the PR in curation_concerns is not passing travis.
