### ISSUE TITLE
ImageMagick issues redux

### ISSUE THREAD

**Issue by acozine** [curationexperts/goldenseal#222]
Resque failure:

```
`mogrify -resize 200x150> /tmp/mini_magick20151027-7177-sfwhuv.jp2` failed with error: mogrify: Problem with skipping JPEG2000 box, stream error `OpenJP2' @ error/jp2.c/JP2ErrorHandler/193. mogrify: unable to decode image file `/tmp/mini_magick20151027-7177-sfwhuv.jp2' @ error/jp2.c/ReadJP2Image/384. 

/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/shell.rb:18:in `run'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:79:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/tool.rb:40:in `new'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/image.rb:494:in `mogrify'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/mini_magick-4.3.6/lib/mini_magick/image.rb:388:in `method_missing'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:32:in `block in create_resized_image'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:38:in `create_image'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:31:in `create_resized_image'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:25:in `process_without_timeout'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/processors/image.rb:8:in `process'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/runners/runner.rb:32:in `block (2 levels) in create'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/runners/runner.rb:29:in `each'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/runners/runner.rb:29:in `block in create'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/curation_concerns-models-0.2.0/app/services/curation_concerns/local_file_service.rb:7:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/runners/runner.rb:43:in `source_file'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/hydra-derivatives-3.0.0/lib/hydra/derivatives/runners/runner.rb:28:in `create'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/curation_concerns-models-0.2.0/app/models/concerns/curation_concerns/file_set/derivatives.rb:39:in `create_derivatives'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/curation_concerns-models-0.2.0/app/jobs/create_derivatives_job.rb:8:in `perform'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:32:in `block in perform_now'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `block in tag_logger'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:43:in `tag_logger'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `instance_exec'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:342:in `block in simple'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:31:in `perform_now'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/execution.rb:21:in `execute'
/opt/goldenseal/shared/bundle/ruby/2.2.0/gems/activejob-4.2.4/lib/active_job/queue_adapters/resque_adapter.rb:46:in `perform'
```

**Comment by acozine** [comment]
The issue above seems to be caused by bad jp2 files in the Schiele collection (the Civil War images). This issue persists on versions 6.9.1 and 6.9.2 of Image Magick.
Upgrading to ImageMagick 6.9.2-4 introduces another error in the derivatives jobs that create the thumbnail images:

```
`mogrify -resize 200x150> /tmp/mini_magick20151029-23754-j1bmf6.tif` failed with error: mogrify: pixel cache allocation failed `/tmp/mini_magick20151029-23754-j1bmf6.tif' @ error/cache.c/OpenPixelCache/3559. mogrify: memory allocation failed `/tmp/mini_magick20151029-23754-j1bmf6.tif' @ error/psd.c/ReadPSDChannelRLE/888.
```

I downgraded to ImageMagick 6.9.1-10 based on http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=28371 - the downgrade took care of the pixel cache allocation error, but reintroduced an issue in the viewer, where ImageMagick cannot handle files without file-type extensions (e.g. myfile vs myfile.jp2). See #104. 

So currently we can ingest with version 6.9.1-10 and we can view objects with 6.9.2-4, but we cannot do both on a single version of ImageMagick.

**Comment by acozine** [comment]
Installed the head of the ImageMagick 6 branch from Github, and so far no issues. Display works, ingest works. Checking the version shows 6.9.2-5, and apparently an official release is imminent.
