### ISSUE TITLE
Can't characterize jp2

### ISSUE THREAD

**Issue by jcoyne** [curationexperts/goldenseal#74]
Possibly due to fits 0.6.0 instead of 0.6.2

```
    job_class: CharacterizeJob
    job_id: 5c427076-5486-43fa-b565-9fb35fe2c97b
    queue_name: characterize
    arguments:
    - zk51vg76b
    locale: en

Exception
    OM::XML::TemplateMissingException
Error
    Cannot insert nodes into the document because it is empty. Try defining self.xml_template on the FitsDatastream class.

    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:193:in `build_ancestors'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:131:in `term_values_append'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:107:in `block in assign_nested_attributes_for_collection_association'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:104:in `each'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:104:in `each_with_index'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:104:in `assign_nested_attributes_for_collection_association'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:46:in `block in update_values'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:43:in `each'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:43:in `inject'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/om-3.1.0/lib/om/xml/term_value_operators.rb:43:in `update_values'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/om_datastream.rb:128:in `update_values'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/om_datastream.rb:104:in `update_indexed_attributes'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/attributes/om_attribute.rb:13:in `writer'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/attributes.rb:111:in `array_setter'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/attributes.rb:66:in `[]='
    /opt/goldenseal/shared/bundle/ruby/2.2.0/gems/active-fedora-9.3.0/lib/active_fedora/attributes.rb:249:in `block in create_attribute_setter'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-c87f4481ec47/curation_concerns-models/app/services/curation_concerns/characterization_service.rb:19:in `characterize'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-c87f4481ec47/curation_concerns-models/app/services/curation_concerns/characterization_service.rb:8:in `run'
    /opt/goldenseal/shared/bundle/ruby/2.2.0/bundler/gems/curation_concerns-c87f4481ec47/curation_concerns-models/app/jobs/characterize_job.rb:6:in `perform'

```

**Comment by jcoyne** [comment]
Fixed by fae877a
